# Generated by Django 4.2.6 on 2024-01-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
    ]
